name: Run tests
on:
  push:
    branches:
      - main
      - test
  pull_request: {}
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r requirements.txt -r dev-requirements.txt
    - name: run tests
      run: ./runtests.sh
